name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # ch·∫°y m·ªói 12 gi·ªù
  workflow_dispatch:       # cho ph√©p ch·∫°y th·ªß c√¥ng

permissions:               # üëà th√™m block n√†y
  contents: write          # cho ph√©p ghi v√†o repo (push branch)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dangkhoi-dev
          outputs: dist/snake.svg

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
